<template>
  <div class="content">
    <div class="container-fluid">
      <md-card>
        <md-card-content style="padding: 36px">
        <div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h1 style="text-align: center; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;" align="center"><span lang="EN">Privacy Policy</span></h1>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu&rsquo;s mission is to connect professionals around the world and help them cultivate a network of trusted, business-oriented relationships that they can depend on for their business transactions. Because we recognize the significance of the privacy of our Members, we are committed to being transparent about the data that we collect about our Members and how we use and distribute these data.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_bcz95aeol74m"></a><span lang="EN"><span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span>I.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">Introduction</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_rpzks3htru3f"></a><strong><span lang="EN">Services</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">This Privacy Policy shall apply to Nuclu&rsquo;s platform at&nbsp;</span><span lang="EN"><a title="https://dev-b2b.madeinmars.com/" href="https://dev-b2b.madeinmars.com/"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc;">https://dev-b2b.madeinmars.com/</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">&nbsp;and other Nuclu-related communications and services.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_458mdjbyt31g"></a><strong><span lang="EN">Change</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu (herein referred to as &ldquo;We&rdquo;, &ldquo;Us&rdquo;, or &ldquo;the Company&rdquo;) can make any material modifications or alterations to this Privacy Policy. If we find the need to make material changes, we shall notify you through our platform or by other means so that you can review these changes before they take effect. Your continued use of our services, even after you have been notified of these changes or after these changes have been published, shall be tantamount to your conformance to the updated terms as of the date of their effectivity. Hence, if you object to any of these changes, you may close your account.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_yzk8hmnlef84"></a><span lang="EN"><span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;</span>II.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">Data We Collect</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_fw5temnsbjlv"></a><strong><span lang="EN">Data We Collect</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To create an account with us, you need to provide some of your personal data, including your name, email address, mobile number, and password.&nbsp;&nbsp;In addition to these data, we also collect personal data about you when you or others post content that contains information about you on our services, such as posts, comments, videos, etc.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We receive personal data about you when you use the services of our customers and partners. Note also that any information you submit to us for publication through our platform may be made accessible by any Member of the Nuclu community. Hence, we recommend that you exercise caution when making a decision on which information you will provide us with.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Moreover, there may be information about you that we will automatically collect, such as when you contact us through our customer services department or engage in other user activities, transactions, and interactions while on our platform.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_jwm3sn1syo5v"></a><strong><span lang="EN">Service Use</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We log usage data when you use or access our services, such as when you view or click on content, perform a search, share content, communicate with other Members, or apply for jobs. Logins, cookies, IP addresses, and device information are used to identify you and log down your use.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_x8c8tleiroy3"></a><strong><span lang="EN">Cookies and Similar Technologies</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use cookies and other similar technologies to gather information about your usage of our Services. By accessing and using our services, you agree to our use of cookies and other technologies for the purposes outlined in this Policy.</span></p>
<h4 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_ig1ni356cnfr"></a><span lang="EN">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Technologies We Use</strong></span></h4>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_h97lns5m1t5o"></a><strong><span lang="EN">Cookies</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Cookies are small files placed onto your device that permit Nuclu features and functionality. Any browser that visits our site may receive cookies from us or from third parties (e.g., customers, partners, service providers).</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We generally make use of two types of cookies. Persistent cookies stay in your browser and help us recognize whether you are an existing user or not so that you can easily return to or interact with our services without needing to sign in again. On the other hand, session cookies last only as long the session takes.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_pijbjt8ck7d3"></a><strong><span lang="EN">Pixels</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Pixels are tiny images that we use to learn more about your interactions with web content or email content. They enable us and third parties to easily place cookies on your browser.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_r5g19e7y2cor"></a><strong><span lang="EN">Local Storage</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Local storage enables our site to share data locally on your device and improve your experience with our services.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_tq7rt9xcrxmu"></a><strong><span lang="EN">Other Technologies</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu uses other tracking technologies, including tags and mobile advertising IDs.</span></p>
<h4 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_72wafcxgez5"></a><span lang="EN">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Use of Tracing Technologies</strong></span></h4>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_a16y4bo3i6z4"></a><strong><span lang="EN">Authentication</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use cookies and similar tracking technologies to verify the identity of our Members when they use our services. For Members, these technologies help us personalize their experience in line with their settings, such as when we use these technologies to verify their eligibility for registration on our platform and verify their account.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_p2bqsxeq25lc"></a><strong><span lang="EN">Customized content</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use cookies and similar tracking technologies to customize your experience on our services. For instance, cookies help us remember your previous searches so that we can offer additional information about them when you return to our mobile platform.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_fs7uzicjf3tg"></a><strong><span lang="EN">Performance, Analytics, and Research</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We or our service providers use cookies and similar tracking technologies to help us learn more about the performance of our services and plugins in different areas, as well as help us improve the content and layout of our services in accordance with our Members&rsquo; preferences.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_xsxcjiajynt7"></a><strong><span lang="EN">Plugins</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use cookies and similar tracking technologies to ascertain and measure the performance of the content on and off our platform and your interaction with them.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_q6xszzw6nsys"></a><strong><span lang="EN">Preferences, Services, and Features</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use cookies and similar tracking technologies to enable the functionality of our services and more easily provide you with the features and content of your preference, in conjunction with our plugins.</span></p>
<h5 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_x7z846af3xgj"></a><strong><span lang="EN">Security</span></strong></h5>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use cookies and similar tracking technologies to ensure your security and privacy when you use and interact with our services. These tracing technologies have been implemented to help us assess account security and monitor for possible security attacks.</span></p>
<h4 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_ivdytem10ibj"></a><span lang="EN">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Third Parties</strong></span></h4>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Third parties, comprised of our customers, partners, and service providers, may use cookies and similar tracking technologies in connection with the delivery and use of our services. As an example, third parties may use cookies, pixels, or other similar technologies in their job posts for their own marketing purposes.</span></p>
<h4 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_whtwiyrx937e"></a><span lang="EN">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Your Choices</strong></span></h4>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Take note that you do have choices on how Nuclu utilizes these cookies and tracking technologies. However, if you restrict the ability of the Company to use these cookies and tracking technologies, your overall user experience may not be customized in a way that appeals best to your preferences.</span></p>
<h4 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_mmahcb7ta78t"></a><span lang="EN">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Do Not Track (DNT)</strong></span></h4>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">DNT is a concept that has been encouraged for the Internet industry to establish and implement a mechanism that allows Internet users to control the tracking of their online activities across sites through their browser settings. Consequently, Nuclu does not respond to &ldquo;do not track&rdquo; signals in general.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_le0nq591o6tg"></a><strong><span lang="EN">Your Location and Device</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We receive data from your device and networks when you visit or leave our services, including your location, the site where you came from, the site you go to after visiting our platform, the time of your visit, your IP address, operating system, proxy server, web browser and add-ons, and device identifier and features. If you use a mobile device when you access our services, that device will send us data based on your phone settings.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_65e4mujrmxc2"></a><strong><span lang="EN">Messages</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We gather information about you when you communicate through our services by sending or receiving messages to other users.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_knfrb4oxqxun"></a><strong><span lang="EN">Other</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We strive to continuously improve our services. Hence, we often introduce new features that will enable us to gather information on how we can further improve our platform.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_6aehz4mvoja1"></a><span lang="EN">III.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">How We Use Your Personal Information</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">How we use data concerning you will depend on a lot of factors, such as how you use our services and your choices as reflected in your settings. We use this information to provide, personalize, and improve our services so that they can be more relevant to you.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_elb8qcggsxs9"></a><strong><span lang="EN">Services</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We use your data to authorize access to and use of our services. Our services allow you to connect and stay up-to-date with other professional contacts. Subject to all Members&rsquo; settings, you will be able to see another professional contact&rsquo;s connections to facilitate an exchange of professional opportunities.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Whether you want to invite someone to use our services, to &ldquo;add&rdquo; someone as a &ldquo;friend&rdquo; on the platform, or to accept another Member to become your &ldquo;friend&rdquo;, the choice is all on you. Our services also allow you to keep up with news, events, and ideas from your professional contacts. We use the information we have gathered about you to personalize the services we offer, such as by recommending relevant content and posts on our platform.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Furthermore, our services enable you to explore and be discovered for career opportunities, as well as to collaborate with colleagues and search for potential clients, customers, and partners to do business with. We also use automated systems to provide and recommend content to ensure that our services are relevant to our Members. Aside from that, we will also contact you through email, mobile number, or other ways to enable communications between you and Nuclu or between you and other Members through our services. You may change your preferences about your communication settings at any time if you wish. However, bear in mind that service messages from us are mandatory.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We may use the data of and content posted by Members to invite and communicate with other professionals in order to drive membership growth of the community, promote engagement with our services, help connect professionals to each other, and encourage economic opportunities. We also make use of data to further improve our services and provide you and others with a more intuitive and personalized experience. Additionally, we use data to investigate and resolve complaints regarding issues about our services, as well as investigate or prevent potential fraud or violations of our terms and policies.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_wsbo4mrgl6jl"></a><span lang="EN">IV.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">How We Share Your Personal Information</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_kkyf27z9e4ki"></a><strong><span lang="EN">Our Services</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Your profile is visible to other Members of our online community, subject to your settings and degree of connection with other Members who may decide to view your profile. Our services also allow the viewing and sharing of information, including posts, likes, and comments. For example, when you share a post publicly or comment on the content of another Member, it can be viewed by other community Members, subject to your settings. We may also share or transmit your personal data with our affiliates only when we deem it reasonably necessary to help us develop, maintain, analyze, audit, detect, market, and improve our services and make our services more relevant and useful to our users.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_cvtps8dh7u9u"></a><strong><span lang="EN">Legal Disclosures</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">There may come an instance that we will be required to reveal information about you when required by law or legal processes or when we believe in good faith that disclosure is necessary for the following:</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo3; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">1)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To enforce our agreements with you</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo3; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">2)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To investigate, prevent, or resolve suspected or actual illegal or harmful activities</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo3; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">3)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To assist government enforcement agencies</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo3; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">4)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To protect and secure the integrity of our services</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo3; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">5)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To investigate and defend ourselves against third-party claims and allegations and</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo3; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">6)<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To exercise and preserve the rights and safety of our Nuclu, our Members, and our affiliates.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Unless prohibited by law or some legal process, we may notify Members of legal demands made for their data. While we may dispute such demands on our discretion, we do not promise that we will challenge each and every demand.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_4v1op7mto8ap"></a><span lang="EN"><span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;</span>V.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">Your Choices and Responsibilities</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_a04bf1bk7avb"></a><strong><span lang="EN">Data Retention</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">In general, we retain most of your personal data for as long as your Nuclu account is open or as required for us to be able to provide you with our services. This encompasses the data that you or other parties provide us with, as well as the data that we have generated from your access to and use of our services. In some cases, we may choose to keep some information about you in a de-personified form.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_q99uv5iren72"></a><strong><span lang="EN">Right to Access and Regulate Your Data</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">You have the right to access, modify, correct, update, control, take, or delete your personal data, including the right to control the visibility of some of your data to others. You also have the right to restrict our use of your personal data or ask us to stop using all or part of your data, such as when we have no legal right to do so.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_e0s6jibfq3rq"></a><strong><span lang="EN">Closure of Your Account</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Should you choose to close or delete your Nuclu account, other users will no longer be able to view your personal data on our platform within 24 hours, and we will close your account information within 30 days from your closure. However, we will still retain some of your personal data in a depersonalized form beyond that time span if we find it reasonably necessary to abide by our legal obligations, resolve disputes, meet regulatory requirements, prevent fraud and abuse, maintain the security and privacy of our services, our Members, and our affiliates, and enforce our terms and policies.<br />Nevertheless, information that you shared with others will remain visible even after you delete your account. We do not control any data that other Members may have copied from you.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_gxyrqje55xha"></a><span lang="EN">VI.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">Other Important Information</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_2nipe6poeulq"></a><strong><span lang="EN">Security</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We employ commercially reasonable security safeguards in place to protect and preserve the integrity and accuracy of your personal data. However, while we regularly monitor our systems for any possible vulnerability and security breaches, we cannot guarantee the total security of any information that you provide us with, especially since transmitted over a wireless network such as the Internet. Hence, we advise that you remain vigilant of your settings, account, and personal information at all times.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_vxqbe5uv8hoo"></a><strong><span lang="EN">Lawful Bases</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We shall only collect, process, and use personal information concerning you in areas where we have lawful bases (i.e., where you gave us your consent, where processing your data is necessary for the performance of a contract, and where we have legitimate interests.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Bear in mind that you have the right to decline or to withdraw your consent where you have given it, at any time. You also have the right to give your objection in cases where we rely on legitimate interests.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_kj2jhgg2n4i9"></a><strong><span lang="EN">Direct Marketing and DNS</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We presently do not transmit or share with any third party any of our Members&rsquo; personal data without the permission of our Members. Nonetheless, if you have any questions or complaints about this section of our Privacy Policy, or any part of our terms and policies, do not hesitate to reach us at&nbsp;</span><span lang="EN"><a title="mailto:info@nuclu.com" href="mailto:info@nuclu.com"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc;">info@nuclu.com</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l2 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a style="background-image: url('img/anchor.gif');" name="_tf5f99w97va"></a><span lang="EN">VII.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN">Members and Users from the European Union (EU)</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">This section of the Privacy Policy applies only to Nuclu Members who are registered citizens of the EU or to those who use our platform and services from a member-state of the EU or from the United Kingdom, in the event that the UK departs from the EU.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_3iyacj3kumlr"></a><strong><span lang="EN">Legal Basis for Processing Personal Data</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We collect, process, and use personal information for the purposes set out in this Privacy Policy and on legal bases that will depend on the personal data concerned as well as the specific context in which we gather and process this information. In general, however, we collect and process personal information about our Members only where you have given us your consent, where it is necessary for us to provide you with our services or to adhere to the law or other legal orders given to us, or where it is necessary for our legitimate interests.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">If our legal bases for collecting, using, and processing data is founded on our legitimate interests or on the legitimate interests of our affiliates or other relevant third parties, these interests shall normally be in relation to the operation of our platform, delivery of our services, management of our relationship with our Members, and communication with you as reasonably necessary. While we may have other legitimate interests, we will make them clear to you at the relevant time what these other interests may be. We will also make the details clear to you at the relevant time if we ever need your personal data for us to comply with legal requirements or for us to enter into a contract with you. Moreover, should we ask for this personal information, we will advise you as to their mandatoriness and their possible consequences if you decline to give them.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Should you have any questions or concerns about these legal bases on which we collect and process your personal information, feel free to contact us at&nbsp;</span><span lang="EN"><a title="mailto:info@nuclu.com" href="mailto:info@nuclu.com"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc;">info@nuclu.com</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_ccpwroup7ptk"></a><strong><span lang="EN">International Transfers of Personal Information</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">In line with the delivery of our services and the operation of our online platform, we may transfer your personal information to countries outside of the EU, including to the countries that may or may not provide the same degree of protection and security as your home country (e.g., the United States, China). However, we will continue to adopt&nbsp;&nbsp;the appropriate measures in order to guarantee that the recipients of your personal data shall be obliged to protecting and preserving the confidentiality of your data. We shall also implement the appropriate safeguards to ensure that your personal information shall remain protected and preserved in accordance with this Privacy Policy.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a style="background-image: url('img/anchor.gif');" name="_al6klomrvgx9"></a><strong><span lang="EN">Your Rights</span></strong></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">For Nuclu Members who reside in or are citizens of the EU, please be aware that you also have the following data protection rights which you can exercise anytime:</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The right to request, access, modify, alter, delete, or transfer your personal information</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The right to object to the processing of your personal data when we do so based on our legitimate interests</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The right to ask us to restrict the processing of your personal data</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The right to opt out of any marketing communications that we may send you at any given time. To exercise this right, simply click on the &ldquo;Unsubscribe&rdquo; link in our marketing emails.</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The right to withdraw any consent you may have given us prior to our collection and processing of your personal information. Take note, however, that withdrawing your consent shall not have any effect on the lawfulness of any processing that we may have conducted prior to the withdrawal of your consent. It shall also not affect the processing of any of your personal data that was&nbsp;&nbsp;done on the basis of lawful grounds other than consent.</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The right to complain to a data protection authority about our collection and use of your personal information.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We respond to all communications that we receive from individuals who wish to exercise their above rights in accordance with the relevant data protection laws.</span></p>
</div>
    </md-card-content>
    </md-card>  
    </div>
  </div>
</template>
<script>

</script>
<style>

</style>
