<template>
  <div class="content">
    <div class="container-fluid">
      <md-card>
      <md-card-content style="padding: 36px">
        <div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h1 style="text-align: center; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;" align="center"><span lang="EN">Terms and Conditions</span></h1>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Our mission is to provide a platform where professionals can cultivate a network of trusted business-oriented relationships that they can rely on for greater economic opportunities.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">In connection with this, we are providing these Terms and Conditions to enable the creation and maintenance of a harmonious business environment utilizing these trustworthy business connections.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l1 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a name="_kcwtmyu9ggg"></a><!-- [if !supportLists]--><span lang="EN"><span style="mso-list: Ignore;"><span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span>I.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN">Introduction</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_ehmv1zav5tor"></a><span lang="EN">Contract</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">By clicking &ldquo;Create an Account&rdquo; or similar buttons, registering, accessing, or using our services, you agree to enter into a legally binding Contract with Nuclu (herein referred to as &ldquo;We&rdquo;, &ldquo;Us&rdquo;, or &ldquo;The Company&rdquo;) even if you use our services on behalf of an organization. If you disagree with this Contract or User Agreement, do not click &ldquo;Create an Account&rdquo; or similar buttons, and do not use or access our services in any way. If you wish to terminate this Contract, simply close your account at any time and do not access or use our services again.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_37psgcz11frk"></a><span lang="EN">Services</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">This Contract applies to Nuclu&rsquo;s website at </span><span lang="EN"><a title="https://dev-b2b.madeinmars.com/" href="https://dev-b2b.madeinmars.com/"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc;">https://dev-b2b.madeinmars.com/</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">, Nuclu-branded applications, and other Nuclu-affiliated communications and services stating that they are offered under this Contract. &ldquo;Members&rdquo; of the community refer to those who are registered users of our services and &ldquo;visitors&rdquo; refer to those who have not registered for the use of our services. As a Member or Visitor of our services, the collection, use, and distribution of your personal data shall be subject to this </span><span lang="EN"><a title="http://www.something.com" href="http://www.something.com/"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc; background: yellow; mso-highlight: yellow;">Privacy Policy</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"> and updates.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_7u570pem0lpe"></a><span lang="EN">Change</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We may modify these Terms, Contract, and Policies from time to time. If we find the need to make material changes, we shall notify you through our services or by other means so that you can review these changes before their effectivity. Your continued use of our services even after the publication or notification of these changes shall be tantamount to your conformance to the updated terms as of the date of their effectivity.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l1 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a name="_u9ybju4z00vs"></a><!-- [if !supportLists]--><span lang="EN"><span style="mso-list: Ignore;"><span style="font: 7.0pt 'Times New Roman';">&nbsp; </span>II.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN">Obligations</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_te3ujyulwbq8"></a><span lang="EN">Service Eligibility</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">The services that Nuclu offers shall not be made available for anyone under 16 years old, which shall be taken as the minimum age. But if the law provides that you must be older so that Nuclu can lawfully provide you with our services without the need of parental consent, then such older age shall constitute as the Minimum Age.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Hence, if you desire to use our services, you must agree that: (1) you are at least 16 years old; (2) you will only create, have access to, and use one Nuclu account; (3) you must use your true and complete identity and shall not provide us with false information; and (4) you have not been restricted by Nuclu from accessing our platform and services. Creating an account that violates these conditions shall constitute a breach of these terms and policies.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_1sc5kow6bdpr"></a><span lang="EN">Account Registration and Use</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Members are account holders. Members shall create an account with Nuclu at </span><span lang="EN"><a title="https://dev-b2b.madeinmars.com/" href="https://dev-b2b.madeinmars.com/"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc;">https://dev-b2b.madeinmars.com/</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"> in their own name using a strong password and by doing so, shall agree to: (1) keep their account and password confidential; (2) not transfer or lend any part of their account, identity, or registration; and (3) abide by the law as well as the list of Do&rsquo;s and Don&rsquo;ts in the </span><span lang="EN"><a title="http://www.something.com" href="http://www.something.com/"><span style="font-size: 12.0pt; line-height: 150%; color: #1155cc; background: yellow; mso-highlight: yellow;">Community Guidelines</span></a></span><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">. Members shall be responsible for any act carried out or for anything that happens on or through their account, and so, they shall bear any corresponding liability and consequence unless they report its misuse or close it.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Members also consent to the following:</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><!-- [if !supportLists]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To never embezzle or falsely borrow the identity of others, nor illegally use the identity or registration of others;</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><!-- [if !supportLists]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To never let any third party use their personal account;</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><!-- [if !supportLists]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To never use fake identities or registration;</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><!-- [if !supportLists]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To never register accounts improperly or illegally, either by using software, programs, or other cheating methods; or</span></p>
<p class="MsoNormal" style="margin-left: .25in; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><!-- [if !supportLists]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To never fill up any information during registration that breaches relevant laws and regulations or infringes the rights of others or interferes with or disrupts the normal operations of Nuclu.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_hkbingarr1xt"></a><span lang="EN">Account Security</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To protect and preserve the legitimate rights and interests of the users of our platform, Nuclu reserves the right to refuse to provide our services and/or to take control measures against accounts that are found to be or are suspected to be having potential security risks or unusual data activities that may endanger the community or the public.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_hi3otzwyalzc"></a><span lang="EN">Notices and Messages</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">As Members, you consent to us providing you with notices and messages in the following ways: (1) within the service; or (2) through the contact information you provided us with, including your email address, mobile number, or physical address. You also agree to update your contact information whenever applicable.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_77f17zbroagi"></a><span lang="EN">Sharing</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Our services allow the sharing of information in various ways. Take note that the information and content you share or post may be seen by other Members or visitors depending on your account settings. We have no legal obligation to publish any information or content on or through our services and, therefore, we can remove such content or information without prior notice.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_rdwkj7szslz5"></a><span lang="EN">Information Publishing</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Members are obliged to publish information in accordance with the relevant publishing rules of Nuclu. The content or information published by Members of Nuclu shall comply with the rules and regulations of their region, country, and jurisdiction, the requirements of their domestic regulatory agencies, and the management rules and regulations of Nuclu on information publishing as well as other pertinent rules and policies.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l1 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a name="_9xcoyoxgyjpk"></a><!-- [if !supportLists]--><span lang="EN"><span style="mso-list: Ignore;">III.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN">Rights and Limits</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_mxdpj8eezn2d"></a><span lang="EN">Your Right to Your Content</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">As between you and Nuclu, you own all the information and content that you post to our online platform. However, you also grant us and our affiliates a non-exclusive, transferrable, and sublicensable license to copy, modify, distribute, use, publish, or process the content in any part of the globe as Nuclu may see fit, without any prior consent, notice, or compensation necessary.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">These rights shall be restricted when you delete such content from our platform or when you close your account, except to the extent that you shared it with other people on the online platform who subsequently copied, distributed, or stored it and except also for the reasonable amount of time that it takes to remove the content or information from our systems.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We may make format changes to and edit your content as necessary, but we will not modify the meaning in any way. Furthermore, since you have the right of ownership over the content and information, and we only possess non-exclusive rights, you may decide to make the content available to others.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">You acknowledge and agree that Nuclu may gain access to, store, process, and use any content or information that you provide us with, subject to our Privacy Policy, other relevant company policies, and your choices.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">By submitting feedback regarding our services, you conform to Nuclu having the right, but not the obligation, to use and share such feedback for any purpose without any compensation to you or to others.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_yz12z7cqmxab"></a><span lang="EN">Service Availability</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu may modify, suspend, or discontinue any part of our services upon reasonable notice to Members to the extent permitted under relevant laws, rules, and regulations. In this connection, we have no obligation to keep, store, maintain, or provide you with a copy of any of the content or information that you provide unless required by applicable laws, rules, and regulations and subject to our company terms and policies.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_f9s737z50z8n"></a><span lang="EN">Limits</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu reserves the right to limit your use and access to our services, including your ability to reach out to other Members. We reserve the right to limit, suspend, or terminate your account if it is found that you are illegally using our services or are in violation of this Contract or the applicable laws, rules, and regulations.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_2dpgaqn27hn0"></a><span lang="EN">Intellectual Property Rights</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu reserves all our intellectual property rights in the services that we provide. Trademarks, logos, and other graphics used for our services are considered trademarks or are registered trademarks of Nuclu.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_jbmko92zfb8m"></a><span lang="EN">Other Content, Sites, and Apps</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">When using our online platform, you may come across content or information that might be incomplete, inaccurate, misleading, illegal, offensive, or otherwise harmful in any way. Nuclu generally does not review content or information provided by Members, so we are not responsible for any of the content or information that you or other Members post or submit to the platform. While we do our utmost to ensure that our services are used only in accordance with our company terms and policies, we cannot always prevent the misuse of our services. Hence, we are not accountable for any such misuse of these services.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu merely offers a platform where Members offering their products/services are able to connect with Members seeking such products/services and does not have anything to do with the performance of or any agreement reached in connection with these products/services.</span></p>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To be eligible for the procuring of or for the performance of these product/service offers, you must be at least 18 years old. You also acknowledge that Nuclu does not supervise, monitor, direct, or control Members in the performance or procurement of these offers, nor do we endorse any product/service offered by any particular Member. Moreover, you agree that nothing creates an employer-employee, agency, or joint venture relationship between Nuclu and any Member who offers their own products/services.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l1 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a name="_fby4hg6d5q1t"></a><!-- [if !supportLists]--><span lang="EN"><span style="mso-list: Ignore;">IV.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN">Online Trading</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_fg1isbpyntve"></a><span lang="EN">Trading</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu encourages its Members to conduct online cross-border trading through the Company&rsquo;s mobile platform and related technical services offered by Nuclu. Transactions done online have to abide by the relevant agreements between the parties as well as the trading rules and policies of Nuclu.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_vw534jlv70q0"></a><span lang="EN">Honest Performance</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To maintain an honest and safe business environment, as well as a healthy and orderly order on the mobile marketplace, Nuclu has the right to deal with acts and conduct that violate the principle of good faith and involve crooked transactions. Nuclu shall also control and enforce punitive measurements on rule-breaking Members in accordance with the information and reports that the Company obtained. It also reserves the right to recover any interests improperly obtained by rule-breaking Members and the losses suffered by Nuclu and the relevant parties.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_um49x5t2x09y"></a><span lang="EN">Offline Disputes</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Unless there is evidence to the contrary, Nuclu shall not be responsible for any disputes or controversy arising out of business-to-business transactions done offline and outside of the mobile marketplace as well as other services provided by Nuclu.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l1 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a name="_jhymjos5yxhx"></a><!-- [if !supportLists]--><span lang="EN"><span style="mso-list: Ignore;"><span style="font: 7.0pt 'Times New Roman';">&nbsp; </span>V.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN">Legal Disclaimers and Limits of Liabilities</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_fxur66z2pqsn"></a><span lang="EN">No Warranty</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Nuclu and its affiliates do not make any representation or warranty about the quality, safety, or reliability of the services or products offered by the Members on the platform. We disclaim any express or implied warranty to the fullest extent allowed under applicable laws, rules, and regulations, including but without limitation to implied warranty of title, non-infringement, accuracy of data, and merchantability or fitness for a particular purpose.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_xzysuqqxc20t"></a><span lang="EN">Exclusion of Liabilities</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">To the fullest extent provided for under relevant laws, rules, and regulations, and unless Nuclu enters into separate written agreements that override this Contract, Nuclu and its business affiliates shall not be liable for any lost profits, lost business opportunities, lost or misused data, smeared reputation, or any consequential, incidental, indirect, punitive, or special damages arising out of this Contract or out of your use of and access to our services. These limitations shall be applicable to all claims of liability, except in cases of death, personal injury, fraud, gross negligence, intentional misconduct, or negligence, where a material obligation that forms a prerequisite to how we deliver our services and on which you may reasonably depend has been violated. However, these exceptions shall only be applied to the extent that the violations or breach committed directly caused the damages.</span></p>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in; margin-left: .25in; margin-right: 0in;">
<h2 style="margin-left: .25in; text-align: justify; text-indent: -.25in; mso-text-indent-alt: -.25in; line-height: 150%; mso-list: l1 level1 lfo1; mso-border-between: 0in none black; mso-padding-between: 0in;"><a name="_n011o55er71a"></a><!-- [if !supportLists]--><span lang="EN"><span style="mso-list: Ignore;">VI.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN">Complaints and Termination of Contract</span></h2>
</div>
<div style="mso-element: para-border-div; border: none black 1.0pt; mso-border-alt: none black 0in; padding: 0in 0in 0in 0in;">
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_i5e8sb3adfi8"></a><span lang="EN">Complaints</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">We respect the rights of each and every individual, as we desire to provide a platform that contains no content violative of any person&rsquo;s rights. For this reason, we require each and every Member of our Nuclu community to distribute or share only accurate information that neither violates nor infringes the rights of other parties. Should you find any content or information posted on our platform objectionable or should you have any concerns about them, kindly reach out to us so that we can address the issue right away.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_vi40bbxiz5he"></a><span lang="EN">Termination of Contract</span></h3>
<p class="MsoNormal" style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><span lang="EN" style="font-size: 12.0pt; line-height: 150%;">Both Members and Nuclu may terminate this Contract at any given time with notice to the other party. On termination, the Member involved loses the right to access or use our Services. On the other hand, Nuclu retains the right to use and/or disclose your feedback following the termination.</span></p>
<h3 style="text-align: justify; line-height: 150%; mso-border-between: 0in none black; mso-padding-between: 0in; padding-top: 0in; mso-padding-top-alt: 0in; padding-bottom: 0in; mso-padding-bottom-alt: 0in; border-bottom: 0in none black; mso-border-bottom-alt: 0in none black;"><a name="_8qpqll24dx2s"></a><span lang="EN">Governing Law</span></h3>
<span lang="EN" style="font-size: 12.0pt; line-height: 115%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial; mso-ansi-language: EN; mso-fareast-language: EN-US; mso-bidi-language: EN-US;">In the unlikely event that a Member ends up in a legal dispute with Nuclu, both parties agree to resolve the matter before the courts of California, U.S.A using California laws.</span></div>
    </md-card-content>
    </md-card>
    </div>
  </div>
</template>
<script>

</script>
<style>

</style>
